version: '3.9'

#https://github.com/compose-spec/compose-spec/blob/master/spec.md#using-extensions-as-fragments
x-logging:
    &default-logging
    options:
        max-size: "100m"
        max-file: "5"
    driver: json-file

x-hasura-env-vars:
    &hasura-env-vars
    HASURA_GRAPHQL_ADMIN_SECRET: CHANGEME-4cPmnM34

services:
    backend:
        image: ${COMPOSE_PROJECT_NAME}:latest
        container_name: backend
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        ports:
            - "8002:80"
        volumes:
            - ..:/code
        depends_on:
            - mongo
        environment:
            MONGO_USER: "${MONGO_USER}"
            MONGO_PASSWORD: "${MONGO_PASSWORD}"
            MONGO_DB: "${MONGO_DB}"
            MONGO_HOST: "${MONGO_HOST}"
            MONGO_PORT: "${MONGO_PORT}"
            SECRET_KEY: "${SECRET_KEY}"
            ALGORITHM: "${ALGORITHM}"
            ACCESS_TOKEN_EXPIRE_MINUTES: "${ACCESS_TOKEN_EXPIRE_MINUTES}"
            MONGO_SERVER_SELECTION_TIMEOUT_MS: "${MONGO_SERVER_SELECTION_TIMEOUT_MS}"
            PYTHONUNBUFFERED : "${PYTHONUNBUFFERED}"
            ELASTICSEARCH_HOSTS : http://elasticsearch:9200


    mongo:
        image: mongo:4.4.4
        container_name: mongodb
        restart: always
        ports:
            - ${MONGO_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - ./init-mongo-db.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/"


    waitfor-db:
        container_name: waitfor-db
        image: dadarek/wait-for-dependencies
        depends_on:
            - mongo
        command: mongo:27017

    init-db:
        container_name: init-db
        image: ${COMPOSE_PROJECT_NAME}:latest
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        environment:
            MONGO_USER: "${MONGO_USER}"
            MONGO_PASSWORD: "${MONGO_PASSWORD}"
            MONGO_DB: "${MONGO_DB}"
            MONGO_HOST: "${MONGO_HOST}"
            MONGO_PORT: "${MONGO_PORT}"
        working_dir: /code
        volumes:
            - ..:/code
        depends_on:
            - waitfor-db

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
        ulimits:
            memlock:
                soft: -1
                hard: -1
        environment:
            - xpack.security.enabled=false
            - "discovery.type=single-node"
            - ES_JAVA_OPTS=-Xms750m -Xmx750m
        ports:
            - 9200:9200  
      
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:8.5.3
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601

volumes:
    backend:
        name: "backend"
