version: '3.9'

#https://github.com/compose-spec/compose-spec/blob/master/spec.md#using-extensions-as-fragments
x-logging:
    &default-logging
    options:
        max-size: "100m"
        max-file: "5"
    driver: json-file

x-hasura-env-vars:
    &hasura-env-vars
    HASURA_GRAPHQL_ADMIN_SECRET: CHANGEME-4cPmnM34

services:
    backend:
        image: ${COMPOSE_PROJECT_NAME}:latest
        container_name: backend
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        ports:
            - "8002:80"
        volumes:
            - ..:/code
        depends_on:
            - mongo
        environment:
            MONGO_USER: "${MONGO_USER}"
            MONGO_PASSWORD: "${MONGO_PASSWORD}"
            MONGO_DB: "${MONGO_DB}"
            MONGO_HOST: "${MONGO_HOST}"
            MONGO_PORT: "${MONGO_PORT}"
    
    mongo:
        image: mongo:4.4.4
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/"


    waitfor-db:
        image: dadarek/wait-for-dependencies
        depends_on:
            - mongo
        command: mongo:27017

    init-db:
        image: ${COMPOSE_PROJECT_NAME}:latest
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        environment:
            MONGO_USER: "${MONGO_USER}"
            MONGO_PASSWORD: "${MONGO_PASSWORD}"
            MONGO_DB: "${MONGO_DB}"
            MONGO_HOST: "${MONGO_HOST}"
            MONGO_PORT: "${MONGO_PORT}"
        working_dir: /code
        volumes:
            - ..:/code
        depends_on:
            - waitfor-db

volumes:
    backend:
        name: "backend"
